---
- name: Archer
  hosts: localhost
  become: "yes"
  roles:
    - { role: timezone, tags: ['timezone'] }
    - locale
    - { role: hostname, tags: ['hostname'] }
    - { role: initramfs, tags: ['initramfs'] }
    - { role: bootloader, tags: ['bootloader'] }
    - networkd
    - wpa_supplicant
    - unbound
    - { role: sxhkd, tags: ['sxhkd'] }
    - { role: andrewrothstein.bash, tags: ['andrewrothstein.bash'] }
    - zsh
    - background
    - x
    - lightdm
    - screensaver
    - user
    - sudo
    - aur
    - pacman
    - journald
    - cronie
    - glances
    - sshd
    - fonts
    - iptables
    - nettools
    - sound
    - bluetooth
    - hostsctl
    - udisks
    - ntp
